name: NightMain
version: '${project.version}'
main: com.foxdev.nightmain.NightMain
commands:
  regels:
    description: Regels!
  punish:
    permission: night.punish
    description: Punish
  freeze:
    description: Freeze
    permission: night.freeze
  pvpon:
    description: Pvp on
    permission: night.pvpon
  pvpoff:
    description: Pvp off
    permission: night.pvpoff